# Generated by Django 5.0.4 on 2026-04-15 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_familycategory_familymember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'version', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TriageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('option_order', models.PositiveIntegerField(default=0)),
                ('flag_effect', models.CharField(choices=[('NONE', 'None'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='NONE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('option_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TriageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('help_text', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_start_question', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='triage.triageflow')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TriageOptionTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_flag', models.CharField(blank=True, choices=[('NONE', 'None'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=10, null=True)),
                ('end_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transition', to='triage.triageoption')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transitions', to='triage.triagequestion')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='triageoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='triage.triagequestion'),
        ),
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('final_flag', models.CharField(blank=True, choices=[('NONE', 'None'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=10, null=True)),
                ('final_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='triage.triagequestion')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_sessions', to='accounts.familymember')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='triage.triageflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TriageSessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_order', models.PositiveIntegerField()),
                ('question_text_snapshot', models.TextField()),
                ('option_label_snapshot', models.CharField(max_length=255)),
                ('option_flag_snapshot', models.CharField(blank=True, choices=[('NONE', 'None'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=10, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_answers', to='triage.triageoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_answers', to='triage.triagequestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='triage.triagesession')),
            ],
            options={
                'ordering': ('answer_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='triagequestion',
            constraint=models.UniqueConstraint(fields=('flow', 'code'), name='unique_question_code_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='triageoption',
            constraint=models.UniqueConstraint(fields=('question', 'code'), name='unique_option_code_per_question'),
        ),
        migrations.AddConstraint(
            model_name='triagesessionanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_question_per_session'),
        ),
        migrations.AddConstraint(
            model_name='triagesessionanswer',
            constraint=models.UniqueConstraint(fields=('session', 'answer_order'), name='unique_answer_order_per_session'),
        ),
    ]
